
modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="neo_favorite_items"
version="${version}"
displayName="New Item Favorites"
displayTest="NONE"
description='''
A versatile item favorites/lock mod for Minecraft
'''

[[mixins]]
config="neo_favorite_items.forge.mixins.json"

[[mixins]]
config="neo_favorite_items.forge.compat.mixins.json"
