
modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="neo_favorite_items"
version="${version}"
displayName="New Item Favorites"
description='''
A versatile item favorites/lock mod for Minecraft
'''

[[mixins]]
config="neo_favorite_items.neoforge.mixins.json"

[[mixins]]
config="neo_favorite_items.neoforge.compat.mixins.json"
