
modLoader="neoforge"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="neo_favorite_items"
version="${version}"
displayName="New Item Favorites"
description='''
A versatile item favorites/lock mod for Minecraft
'''
